#!/bin/tcsh
#this script is wrapper of "rm_tmpfile.csh"
set GIT_ROOT = `git rev-parse --show-toplevel`
set INST_DIR = "$GIT_ROOT/scripts/utility/rm_tmpfile"
set CMD      = "$INST_DIR/rm_tmpfile.csh"
  tcsh $CMD
